version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: Install dependencies
                  command: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run:
                  name: Build
                  command: NODE_ENV=development yarn build

            - run:
                  name: Install zip
                  command: sudo apt-get install zip

            - run:
                  name: Create release zipfile
                  command: yarn zip

            - run:
                  name: Set env vars
                  command: |
                      echo "export ts=$(date +%Y%m%d-%H%M%S)" >> $BASH_ENV
                      echo "export tmpfolder=/var/www/sites/manuelbieh.de/tmp" >> $BASH_ENV
                      echo "export target=/var/www/sites/manuelbieh.de" >> $BASH_ENV
            - run:
                  name: Add host to known_hosts
                  command: ssh-keyscan manuelbieh.de >> ~/.ssh/known_hosts

            - run:
                  name: Deploy
                  command: |
                      ssh circleci@manuelbieh.de rm -rf ${tmpfolder}
                      ssh circleci@manuelbieh.de mkdir -p ${tmpfolder}
                      ssh circleci@manuelbieh.de mkdir -p ${target}/releases/${ts}
                      scp ~/repo/release.zip circleci@manuelbieh.de:${target}/tmp
                      ssh circleci@manuelbieh.de unzip ${tmpfolder}/release.zip -d ${target}/releases/${ts}
                      ssh circleci@manuelbieh.de rm -rf ${target}/htdocs
                      ssh circleci@manuelbieh.de ln -s ${target}/releases/${ts} ${target}/htdocs
